### PR TITLE
iter_all() Automatic Paging

### PR DESCRIPTION
**Pull request by surbas**
#### What?

Main thing is I added automatic paging to the `all` method of `ListableApiResource`.  With this pull it returns a generator with _all_ of the objects. It does this by requesting pages from the api till it returns a empty list.

Also cleaned up some warts i found while going thought the code.

Happy to take a similar approach for ListableApiSubResource resource however I am not sure of the semantics of paging subresources.

### CODE REVIEW

**Comment by surbas** [comment]
@bc-jackiehuynh and @bookernath sorry to blast but trying to get some eyes on this. All test pass. Please let me know thoughts!

**Comment by surbas** [comment]
TBH I can't think of a better name... i guess `iterall` or `generative_all`... I would argue this is an acceptable breaking change as it does what the README saids should happen (i was very surprised that `all` didn't actually get all). As this lib is still before 1.0 status I would argue breaking changes should be expected by users. We could bump this to 0.18 (or 1.0 even) and flag it as a breaking change. 

Happy to also make a new function if that is too big of a leap for now. Let me know either way and a preference for names.

**Comment by surbas** [comment]
@bookernath just bumping my previous response...

**Comment by bookernath** [comment]
.all() is essentially collection GET whereas .get() is single object GET.

If you want to spin off a new method (given the new return type) and call it something like .paginate_all() I'd be totally comfortable.

That way any of the people using this for production usage (I notice 50+ forks) can safely upgrade to this and future versions that may introduce bug fixes and other things, without having to adapt their code around pagination or multi-threading.

As an example, here's some code I've written to GET all Customers:

`#iterate through the pages
for currentPage in range(1, (numPages+1)):
    #get the entire page as an object
    currentPageOfCustomers = api.Customers.all(page=currentPage, limit=pageSize)
    s = Thread(target=processPageOfCustomers, args=(currentPageOfCustomers,))
    s.start()`

This code would break with your change I'm pretty sure.

If at all possible, let's make an additive and backwards compatible change. :)

**Comment by surbas** [comment]
So in the case you just illustrated This code works the same.... `currentPageOfCustomers` will be an iterable just like it was before. Each thread will be able to process the current page. And as each thread is getting its own page it is all thread safe. I posit in most cases one will be just `for`'ing through through the iterable. If you noticed I didn't break any tests related to this change. All of the use cases you supported continue to be supported. The only cases where this fail is you were treating the collection as a stack for some reason, and then I would argue that the programmer is doing something wrong... with that said is changing the name the only thing i need to do? You are happy with the rest? 
I will update the pull with new name. :)

**Comment by bookernath** [comment]
Yes I'm totally happy if the change is additive with a new method.

**Comment by surbas** [comment]
@bookernath updated as requested.

**Comment by bookernath** [comment]
Awesome, thanks for your contribution @surbas !

**Pull request merged**
