### PR TITLE
Do not use mutable objects as default arguments.

### PR DESCRIPTION
**Pull request by Anmol-Gulati**
REF: http://docs.python-guide.org/en/latest/writing/gotchas/

### CODE REVIEW

**Comment by Anmol-Gulati** [comment]
Even if you use an empty dictionary as default argument in `_run_method` and `make_request`, you are still passing `None` in `_make_request` which will override the empty dictionary in `make_request` and further resulting in overriding the empty dictionary in `_run_method`.

And it is not at all good practice to pass in `Mutable Objects` as default arguments. REF: http://docs.python-guide.org/en/latest/writing/gotchas/

**Comment by Anmol-Gulati** [comment]
@bookernath Requesting review. It is a bug and is throwing `not a valid non-string sequence or mapping object` error. I have already tested this fix on my local environment and is working fine.

**Comment by Anmol-Gulati** [comment]
@bookernath Thanks for merging, when can I expect this to release?

**Comment by bookernath** [comment]
@Anmol-Gulati just pushed it!

**Pull request merged**
