### PR TITLE
Prepare for 0.11.0 release

### PR DESCRIPTION
**Pull request by mattolson**
* Update package definition in setup.py
* Update changelog
* Update license year
* Switch to Restructured Text for README so we can use the same file for GitHub and PyPi
* Minor updates in README

### CODE REVIEW

**Comment by gabelimon** [comment]
:+1:

**Comment by hockeybuggy** [comment]
Yay! :fireworks: 

I am wondering if the next version should be `0.11.0`? In my opinion there are enough changes to warrant more than a patch increment.

**Comment by gabelimon** [comment]
I'd like to reserve major versions for interface changes but I'm flexible.

**Comment by hockeybuggy** [comment]
I think adding the webhooks resource as well as adding `count` method to many of the resources could be considered an interface change. I don't think there are any breaking changes, so a full major version isn't needed, but a minor would be nice.

**Comment by mattolson** [comment]
OK @hockeybuggy I agree, I'll update to `0.11.0`.

**Comment by hockeybuggy** [comment]
Thanks @gabelimon and @mattolson! I am excited to use this!

**Comment by mattolson** [comment]
Released: https://pypi.python.org/pypi/bigcommerce

**Pull request merged**
